config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  resource :user, only: %i[show]

  get 'deposit', to: 'accounts#new'
  post 'deposit', to: 'accounts#deposit'

  resource :wallet, only: %i[show new create]

  get 'wallet/deposit', to: 'wallets#deposit_new'
  post 'wallet/deposit', to: 'wallets#deposit'

  get 'wallet/withdraw', to: 'wallets#withdraw_new'
  post 'wallet/withdraw', to: 'wallets#withdraw'

  post 'authorization', to: 'authorizations#index'
end

app/models/user.rb
# frozen_string_literal: true

# ユーザーモデル
class User < ApplicationRecord
  validates :username, presence: true, length: { maximum: 255 }, uniqueness: true
  # validates :first_name, presence: true, length: { maximum: 255 }
  # validates :last_name, presence: true, length: { maximum: 255 }
  # validates :phone_number, presence: true, length: { maximum: 255 }
  # validates :email, presence: true, length: { maximum: 255 }

  has_one :account
  has_one :wallet
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :signed_in?, only: %i[show]

  def show
    @user = current_user
  end

  def new; end

  def create
    user = User.new(user_params)
    user.build_account.save!
    user.build_wallet.save!
    services_json = {
                     "services": [
                       {
                         "id": 'quattrowallet',
                         "type": 'QuattroWallet',
                         "serviceEndpoint": "https://issuer.quattro.example.com/wallets/#{user.wallet.id}"
                       }
                     ]
                   }.to_json

    response = Net::HTTP.post(
      URI("#{ENV['DID_SERVICE_URL']}/did/create"),
      services_json,
      'Content-Type' => 'application/json'
    )
    body = JSON.parse(response.body)
    did_long_form = body['did']
    signing_key = body['signingKey'].to_json
    recovery_key = body['recoveryKey'].to_json
    update_key = body['updateKey'].to_json

    Did.create!(wallet: user.wallet, did_long_form:, signing_key:, recovery_key:, update_key:)

    sign_in(user)

    redirect_to wallet_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :phone_number, :email)
  end
end

app/views/users/new.html.erb
<h2>
  Sign Up
</h2>

<%= form_with scope: :user, url: signup_path do |form| %>
  <div>
    <%= form.text_field :username, placeholder: "User Name", required: true %>

    <%= form.submit "Sign Up" %>

    <div>
      <p>
        Already have an account?
        <%= link_to "Login", login_path %>
      </p>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div>
  <div>
    <h2>
      User information
    </h2>

    <div>
      <%= link_to deposit_path do %>
        <div>
          <div>
            Account Balance
          </div>
          <div>
            <%= number_to_currency(current_user.account.balance) %>
          </div>
        </div>
      <% end %>
    </div>

    <% if current_user.wallet.present? %>
      <div>
        <%= link_to wallet_path do %>
          <div>
            <div>
              Wallet Balance
            </div>
            <div>
              <%= number_to_currency(current_user.wallet.balance) %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

    <div>
      <%= button_to 'Log out', logout_path, method: :delete %>
    </div>

    <%= form_with scope: :user, url: user_path do |form| %>
      <div>
        <div>
          <%= form.text_field :first_name, readonly: true %>
          <%= form.text_field :last_name, readonly: true %>
        </div>
        <%= form.text_field :username, readonly: true %>
        <%= form.text_field :phone_number, readonly: true %>
        <%= form.text_field :email, readonly: true %>
      </div>
    <% end %>

  </div>
</div>


<div>

</div>