config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  resource :user, only: %i[show]

  get 'deposit', to: 'accounts#new'
  post 'deposit', to: 'accounts#deposit'

  resource :wallet, only: %i[show new create]

  get 'wallet/deposit', to: 'wallets#deposit_new'
  post 'wallet/deposit', to: 'wallets#deposit'

  get 'wallet/withdraw', to: 'wallets#withdraw_new'
  post 'wallet/withdraw', to: 'wallets#withdraw'

  post 'authorization', to: 'authorizations#index'
end

app/models/wallet.rb
# frozen_string_literal: true

# ウォレットモデル
class Wallet < ApplicationRecord
  validates :glueby_wallet_id, presence: true

  belongs_to :user, optional: true
  has_one :did

  after_initialize do
    self.glueby_wallet_id ||= Glueby::Wallet.create.id
  end

  def self.utxo_provider_wallet
    find_by(glueby_wallet_id: 'UTXO_PROVIDER_WALLET')
  end

  def balance
    Token.instance.glueby_token.amount(wallet: glueby_wallet)
  end

  def glueby_wallet
    @glueby_wallet ||= Glueby::Wallet.load(glueby_wallet_id)
  end
end

app/controllers/wallets_controller.rb
# frozen_string_literal: true

class WalletsController < ApplicationController
  before_action :signed_in?, only: %i[show new create]
  before_action :has_wallet?, only: %i[show]
  before_action :already_has_wallet, only: %i[new create]

  def show
    @wallet = current_user.wallet
  end

  def new; end

  def create
    current_user.build_wallet.save!

    # DID へ登録する Services を定義する
    services_json = {
                     "services": [
                       {
                         "id": 'quattrowallet',
                         "type": 'QuattroWallet',
                         "serviceEndpoint": "https://issuer.quattro.example.com/wallets/#{current_user.wallet.id}"
                       }
                     ]
                   }.to_json

    # DID Service へ DID の作成依頼を送る
    response = Net::HTTP.post(
      URI('http://localhost:3001/did/create'),
      services_json,
      'Content-Type' => 'application/json'
    )
    body = JSON.parse(response.body)

    # 返答を受け取る
    did_long_form = body['did']
    signing_key = body['singingKey']
    recovery_key = body['recoveryKey']
    update_key = body['updateKey']

    # DID 情報を保存する
    Did.create!(did_long_form:, signing_key:, recovery_key:, update_key:)

    redirect_to wallet_path
  end

  def deposit_new; end

  def deposit
    amount = params[:wallet][:amount].to_i
    account = current_user.account
    Token.instance.reissue!(amount:)
    generate_block
    Token.instance.transfer!(sender: Wallet.utxo_provider_wallet, receiver: current_user.wallet, amount:)
    generate_block
    account.update!(balance: account.balance - amount)

    redirect_to user_path, notice: "Deposit successful."
  end

  def withdraw_new; end

  def withdraw
    amount = params[:wallet][:amount].to_i
    account = current_user.account
    Token.instance.burn!(wallet: current_user.wallet, amount:)
    generate_block
    account.update!(balance: account.balance + amount)

    redirect_to user_path, notice: "Deposit successful."
  end

  private

  def has_wallet?
    redirect_to new_wallet_path unless current_user.wallet
  end

  def already_has_wallet
    redirect_to wallet_path if current_user.wallet
  end

  def generate_block
    utxo_provider_address = Glueby::UtxoProvider.instance.address
    aggregate_private_key = ENV['TAPYRUS_AUTHORITY_KEY']
    Glueby::Internal::RPC.client.generatetoaddress(1, utxo_provider_address, aggregate_private_key)

    latest_block_num = Glueby::Internal::RPC.client.getblockcount
    synced_block = Glueby::AR::SystemInformation.synced_block_height
    (synced_block.int_value + 1..latest_block_num).each do |height|
      Glueby::BlockSyncer.new(height).run
      synced_block.update(info_value: height.to_s)
    end
  end
end

app/views/wallets/deposit_new.html.erb
<div>
  <div>
    <h2>
      Deposit
    </h2>

    <%= form_with scope: :wallet, url: wallet_deposit_path do |form| %>
      <div>
        <%= form.number_field :amount, placeholder: "Amount", required: true %>

        <%= form.submit "Deposit"%>
      </div>
    <% end %>

  </div>
</div>

app/views/wallets/show.html.erb
<div>
  <div>
    <h2>
      Wallet information
    </h2>
    <div>
      <div>

        <div>
          Balance
        </div>
        <div>
          <%= number_to_currency(@wallet.balance) %>
        </div>

      <div>
        <%= link_to 'Deposit', wallet_deposit_path%>
        <%= link_to 'Withdraw', wallet_withdraw_path%>
      </div>
    </div>
  </div>
</div>

app/views/wallets/withdraw_new.html.erb
<div>
  <div>
    <h2>
      Withdrawal
    </h2>

    <%= form_with scope: :wallet, url: wallet_withdraw_path do |form| %>
      <div>
        <%= form.number_field :amount, placeholder: "Amount", required: true %>

        <%= form.submit "Withdrawal"%>
      </div>
    <% end %>

  </div>
</div>